import React, { useState } from 'react';
import { useGameStore } from '../store/useGameStore.js';
import TimedQuestModal from './TimedQuestModal.jsx';
import VerifyProofModal from './VerifyProofModal.jsx';
import { 
  CheckCircle2, 
  Trash2, 
  Sparkles, 
  BookOpen, 
  Dumbbell, 
  Briefcase, 
  Home, 
  Heart, 
  Palette, 
  Coins,
  Bot,
  Timer,
  ShieldCheck
} from 'lucide-react';

const CATEGORY_ICONS = {
  Study: BookOpen,
  Fitness: Dumbbell,
  Work: Briefcase,
  Chores: Home,
  Health: Heart,
  Creative: Palette,
};

const DIFFICULTY_STYLES = {
  Easy: {
    badge: 'bg-emerald-950 text-emerald-300 border-emerald-700',
    dot: 'bg-emerald-500',
  },
  Medium: {
    badge: 'bg-amber-950 text-amber-300 border-amber-700',
    dot: 'bg-amber-500',
  },
  Hard: {
    badge: 'bg-orange-950 text-orange-300 border-orange-700',
    dot: 'bg-orange-500',
  },
  Epic: {
    badge: 'bg-purple-950 text-purple-200 border-purple-600 shadow-glow-xp',
    dot: 'bg-fuchsia-400',
  },
};

export default function QuestCard({ quest, index = 0 }) {
  const { completeQuest, deleteQuest, completingIds } = useGameStore();
  const [showTimedModal, setShowTimedModal] = useState(false);
  const [showVerifyModal, setShowVerifyModal] = useState(false);

  const isCompleted = quest.status === 'Completed';
  const isClaiming = Boolean(completingIds && completingIds[quest._id]);
  const Icon = CATEGORY_ICONS[quest.category] || BookOpen;
  const diffStyle = DIFFICULTY_STYLES[quest.difficulty] || DIFFICULTY_STYLES.Easy;

  return (
    <article
      aria-label={`Quest: ${quest.title}`}
      className={`relative rounded border-2 transition-all duration-200 p-4 shadow-pixel-sm ${
        isCompleted
          ? 'bg-rpg-panel/40 border-rpg-border/40 opacity-60'
          : 'bg-rpg-panel border-rpg-border hover:border-rpg-gold/60 hover:shadow-glow-gold/10 hover:-translate-y-0.5'
      }`}
    >
      {/* Top Banner: Category & Difficulty */}
      <div className="flex items-center justify-between gap-2 mb-2.5">
        <div className="flex flex-wrap items-center gap-1.5">
          {/* Category Chip */}
          <span className="flex items-center gap-1.5 px-2 py-0.5 rounded bg-rpg-dark text-slate-300 text-xs font-mono font-medium border border-rpg-border">
            <Icon className="w-3.5 h-3.5 text-rpg-mana" />
            {quest.category}
          </span>

          {/* Difficulty Badge */}
          <span
            className={`px-2 py-0.5 rounded text-[11px] font-mono font-bold uppercase tracking-wider border flex items-center gap-1 ${diffStyle.badge}`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${diffStyle.dot}`} />
            {quest.difficulty}
          </span>

          {/* Stat Contribution Badge */}
          {quest.statType && (
            <span className="px-1.5 py-0.5 rounded bg-amber-950/50 text-amber-300 border border-amber-800 text-[10px] font-mono capitalize">
              +{quest.difficulty === 'Hard' ? '4' : quest.difficulty === 'Medium' ? '2' : '1'} {quest.statType}
            </span>
          )}

          {/* AI Generated Tag */}
          {quest.isAIGenerated && (
            <span className="px-1.5 py-0.5 rounded bg-fuchsia-950 text-fuchsia-300 border border-fuchsia-800 text-[10px] font-mono flex items-center gap-1" title="Generated by AI Guildmaster">
              <Bot className="w-3 h-3" />
              AI
            </span>
          )}
        </div>

        {/* Delete / Abandon */}
        {!isCompleted && (
          <button
            onClick={() => deleteQuest(quest._id)}
            className="text-slate-500 hover:text-red-400 p-1 transition rounded hover:bg-slate-800 focus-visible:ring-2 focus-visible:ring-red-400"
            title="Abandon Quest"
            aria-label={`Abandon quest: ${quest.title}`}
          >
            <Trash2 className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Quest Title & Lore Description */}
      <div className="mb-4">
        <h3
          className={`font-semibold text-base mb-1 ${
            isCompleted ? 'line-through text-slate-400' : 'text-slate-100'
          }`}
        >
          {quest.title}
        </h3>
        {quest.description && (
          <p className="text-xs text-slate-400 font-sans leading-relaxed line-clamp-2">
            {quest.description}
          </p>
        )}
      </div>

      {/* Bottom Bar: Rewards & Complete Action */}
      <div className="flex items-center justify-between pt-3 border-t border-rpg-border/60">
        {/* Bounty Payout */}
        <div className="flex items-center gap-3">
          {/* XP */}
          <div className="flex items-center gap-1 text-xs font-mono font-bold text-purple-300">
            <Sparkles className="w-3.5 h-3.5 text-purple-400" />
            <span>+{quest.xpReward} XP</span>
          </div>
          {/* Gold */}
          <div className="flex items-center gap-1 text-xs font-mono font-bold text-rpg-gold">
            <Coins className="w-3.5 h-3.5 text-rpg-gold" />
            <span>+{quest.goldReward}g</span>
          </div>
        </div>

        {/* Action Button */}
        {isCompleted ? (
          <span className="flex items-center gap-1 text-xs font-mono font-bold text-emerald-400">
            <CheckCircle2 className="w-4 h-4" />
            Conquered
          </span>
        ) : (
          <button
            disabled={isClaiming}
            onClick={() => {
              if (quest.verificationType === 'Timed') setShowTimedModal(true);
              else if (quest.verificationType === 'Verified') setShowVerifyModal(true);
              else completeQuest(quest._id);
            }}
            aria-label={`Claim glory for ${quest.title}`}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-emerald-600 hover:bg-emerald-500 text-white font-mono text-xs font-bold transition shadow-pixel-sm active:translate-y-0.5 border border-emerald-400 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-emerald-400"
          >
            {isClaiming ? (
              <span className="animate-spin w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full" />
            ) : quest.verificationType === 'Timed' ? (
              <Timer className="w-3.5 h-3.5" />
            ) : quest.verificationType === 'Verified' ? (
              <ShieldCheck className="w-3.5 h-3.5" />
            ) : (
              <CheckCircle2 className="w-3.5 h-3.5" />
            )}
            {isClaiming
              ? 'Claiming...'
              : quest.verificationType === 'Timed'
              ? quest.status === 'InProgress'
                ? 'Resume Trial'
                : 'Start Trial'
              : quest.verificationType === 'Verified'
              ? 'Verify & Claim'
              : 'Claim Glory'}
          </button>
        )}
      </div>
      {showTimedModal && <TimedQuestModal quest={quest} onClose={() => setShowTimedModal(false)} />}
      {showVerifyModal && <VerifyProofModal quest={quest} onClose={() => setShowVerifyModal(false)} />}
    </article>
  );
}
